config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'users#index'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index new create show destroy] do
      resources :comments, only: %i[index create destroy]
      resources :likes, only: %i[index create]
    end
  end

  namespace :api, :defaults => {:format => :json} do 
    post '/auth/login', to: 'authentication#login'
    resources :users, only: %i[index show] do
      resources :posts, only: %i[index new create show destroy] do
        resources :comments, only: %i[index create destroy]
        resources :likes, only: %i[index create]
      end
    end
  end
end

app/views/partials/_card.html.erb
<div id="<%=user.id%> User-card" class="flex items-center gap-3 sm:gap-8 w-full">
  <div class="image-container h-52 w-72">
    <img src=<%= user.photo %> alt="Profile picture of <%= user.name%>" class="border-4 border-solid border-gray-900" />
  </div>
  <div class="relative border-4 border-solid border-gray-900 p-3 sm:p-10 h-48 w-full flex flex-wrap items-center">
    <h2 class="text-3xl  sm:text-4xl" > <%= user.name %> </h2>
    <p class="absolute bottom-4 left-4 text-lg sm:text-xl">Number of Posts: <%= user.posts_counter%> </p>
  </div>   
</div>

app/views/partials/_comment.html.erb
<div class="flex items-center justify-between w-full h-fit p-2 border-b-2 border-solid border-gray-400 comment">
  <p class="text-xl sm:text-2xl"> <strong><%= comment.author.name%>:</strong> <%= comment.text%><p>
  <% if can? :destroy, comment %>
    <%= link_to 'Delete', user_post_comment_path(user_id: current_user.id, post_id: comment.post.id, id: comment.id), method: :delete, class: "block py-1 px-5 bg-red-800 hover:bg-red-700 text-white text-xl" %>      
  <% end%>
</div>

app/views/partials/_comment_form.html.erb
<% if user_signed_in? %>
  <%= form_with model: comment, url: user_post_comments_url(user_id: current_user.id, post_id: post.id), method: :post, class: "p-3 sm:p-10 mt-10 border-solid border-4 border-sky-500" do |f| %>
    <%= f.hidden_field :post, value: post.id %>
    <div class="flex flex-col mb-4">
      <%= f.label :text, class: "text-xl sm:text-2xl" %>
      <%= f.text_area :text, class: "text-xl" %>
    </div>
    <%= f.submit 'Comment', class: "bg-sky-700 text-white px-5 py-2.5 hover:cursor-pointer hover:bg-red-700" %>
  <% end %>
<% else %>
  <h2 class="mt-10 text-3xl"> Log in to add comments, like, and create posts! </h2>
<% end %>

app/views/partials/_like.html.erb
<% if user_signed_in? %>
  <div class="flex sm:absolute top-0 right-0">
    <% if can? :destroy, post %>
      <%= link_to 'Delete', user_post_path(id: post.id, user_id: post.author.id), method: :delete, class: "p-5 bg-red-800 hover:bg-red-700 text-white text-xl" %>      
    <% end%>
    <%= form_with model: like, url: user_post_likes_url(post_id: post.id, user_id: post.author.id), method: 'post' do |f| %>
      <%= f.hidden_field :post, value: post.id %>
      <%= f.submit 'Like', class: "bg-sky-700 text-white text-xl p-5 hover:cursor-pointer hover:bg-sky-600" %>
    <% end %>
  </div>
<% end %>

app/views/partials/_like_flash.html.erb
<% if flash[:liked] || flash[:unliked] %>
  <% flash.each do |type, msg| %>
    <span class="absolute top-0 left-0 px-5 py-2.5 bg-blue-600 text-white z-50" > <%= msg %> </span>
  <% end %>
<% end %>

app/views/partials/_new_post.html.erb
<%= form_with model: post, url: user_posts_url(user_id: current_user.id),method: :post, class: "flex flex-col items-center gap-8 p-3 sm:p-10 mt-10 border-solid border-4 border-sky-500 w-full" do |f| %>
  <%= f.hidden_field :likes_counter, value: 0 %>
  <%= f.hidden_field :comments_counter, value: 0 %>
  <div class="flex flex-col gap-4 w-full">
    <%= f.label :title, class: "text-2xl" %>
    <%= f.text_field :title, class: "text-xl w-full" %>
  </div>
  <div class="flex flex-col gap-4 w-full">
    <%= f.label :text, class: "text-2xl" %>
    <%= f.text_area :text, rows: "14" , class: "text-xl w-full" %>
  </div>
  <%= f.submit 'Create Post', class: "bg-sky-700 text-white px-5 py-2.5 hover:cursor-pointer hover:bg-red-700 max-w-lg" %>
<% end %>

app/views/partials/_post_card.html.erb
<%= link_to user_post_path(user_id: user.id, id: post.id), id: "Post: #{post.id}", class: "w-full" do %>
  <div class="relative border-4 border-solid border-gray-900 sm:h-56 p-3 sm:p-11 w-full flex items-center post">
    <h3 class="absolute text-2xl sm:text-3xl top-3 left-3" > <%= post.title %> </h3>
    <p class="text-lg sm:text-2xl py-16" ><%= truncate(post.text, :length => 150) %></p>
    <p class="absolute right-2 sm:right-4 bottom-4 text-xl"> Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %> </p>
  </div>
<% end %>