config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'users#index'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index new create show destroy] do
      resources :comments, only: %i[index create destroy]
      resources :likes, only: %i[index create]
    end
  end

  namespace :api, :defaults => {:format => :json} do 
    post '/auth/login', to: 'authentication#login'
    resources :users, only: %i[index show] do
      resources :posts, only: %i[index new create show destroy] do
        resources :comments, only: %i[index create destroy]
        resources :likes, only: %i[index create]
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :comments, foreign_key: 'author_id', dependent: :delete_all
  has_many :posts, foreign_key: 'author_id', dependent: :delete_all
  has_many :likes, foreign_key: 'author_id', dependent: :delete_all
  validates :name, presence: true
  validates :posts_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(:created_at)
    @current_user = current_user
  end

  def show
    @user = User.find(params[:id])
  end
end

app/views/users/index.html.erb
<div class="w-full">
  <ul class="flex flex-wrap justify-center w-full gap-5">
    <% @users.each do |user| %>
    <li class="w-full max-w-3xl">
      <%= link_to user_path(id: user.id), class:"w-full", id: "User: #{user.id}" do %>
        <%= render 'partials/card', user: user%>
      <% end %>
    </li>
    <% end %>
  </ul> 
</div>

app/views/users/show.html.erb
<div class="flex flex-col items-center w-full gap-8">
  <div class="w-full max-w-3xl">
    <%= render 'partials/card', user: @user %> 
  </div>
  <div class="p-5 sm:p-10 border-4 border-solid border-gray-900">
    <h2 class="text-3xl mb-7" > Biography </h2>
    <p class="text-xl"> <%= @user.bio %> </p>
  </div>
  <ul class="flex flex-col w-full gap-8">
    <% @user.recent_posts.each do |post| %>
      <li>
        <%= render 'partials/post_card', post: post, user: @user %>
        <% if can? :destroy, post %>
          <%= link_to 'Delete', user_post_path(id: post.id, user_id: post.author.id), method: :delete, class: "p-1 sm:p-5 bg-red-800 hover:bg-red-700 text-white text-lg sm:text-xl flex items-center" %>      
        <% end%>
      </li>
    <% end %>
  </ul>
  <%= link_to 'See more Posts', user_posts_path(user_id: @user.id), class: "px-5 py-2.5 text-2xl bg-sky-800 text-white" %>
</div>