config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'users#index'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index new create show destroy] do
      resources :comments, only: %i[index create destroy]
      resources :likes, only: %i[index create]
    end
  end

  namespace :api, :defaults => {:format => :json} do 
    post '/auth/login', to: 'authentication#login'
    resources :users, only: %i[index show] do
      resources :posts, only: %i[index new create show destroy] do
        resources :comments, only: %i[index create destroy]
        resources :likes, only: %i[index create]
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Primary Meta Tags -->
    <title>Blog App</title>
    <meta name="title" content="Blog App">
    <meta name="description" content="This is a basic Blog website that allows users to create, edit, 
    comment and delete posts, keeping data in a database. This project implements both authorization 
    and authentication in order to provide extended functionality to logged in and authorized users">
      
    <!-- Open Graph / Facebook -->
    <meta prefix="og: http://ogp.me/ns#" property="og:type" content="website">
    <meta prefix="og: http://ogp.me/ns#" property="og:url" content="https://jf-blog-app.herokuapp.com/">
    <meta prefix="og: http://ogp.me/ns#" property="og:title" content="Blog App">
    <meta prefix="og: http://ogp.me/ns#" property="og:description" content="This is a basic Blog website that allows users to create, edit, 
    comment and delete posts, keeping data in a database. This project implements both authorization and authentication in order to 
    provide extended functionality to logged in and authorized users">
    <meta prefix="og: http://ogp.me/ns#" property="og:image" content="<%= image_url('page_preview.png') %>">
      
    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="https://jf-blog-app.herokuapp.com/">
    <meta property="twitter:title" content="Blog App">
    <meta property="twitter:description" content="This is a basic Blog website that allows users to create, edit, comment and delete posts, 
    keeping data in a database. This project implements both 
    authorization and authentication in order to provide extended functionality to logged in and authorized users">
    <meta property="twitter:image" content="<%= image_url('page_preview.png') %>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>    

    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload"   %> 

    <%= stylesheet_link_tag "partials", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <header class="sticky top-0 left-0 flex flex-wrap gap-3 items-center justify-between w-full bg-slate-800 p-5 mb-9 z-40">
      <% if user_signed_in?%>
        <%= link_to "/" do %>
          <h2 class="text-4xl text-white"> Welcome, <%= current_user.name %> </h2>
        <% end %>
        <div class="flex items-center gap-4">
          <%= link_to 'Create New Post', new_user_post_path(user_id: current_user.id), class: "px-5 py-2.5 text-white bg-sky-700 hover:cursor-pointer hover:bg-sky-600" %>
          <%= link_to 'Log out' , destroy_user_session_path, method: :delete, class: "px-5 py-2.5 text-white bg-red-700 hover:cursor-pointer hover:bg-red-800" %>
        </div>
      <% else %>
        <%= link_to "/" do %>
          <h2 class="text-4xl text-white"> Welcome! </h2>
        <% end %>
        <div class="flex flex-wrap items-center gap-4">
          <%= link_to 'Log In', new_user_session_path, class: "px-5 py-2.5 text-white bg-sky-700 hover:cursor-pointer hover:bg-sky-600" %>
        </div>
      <% end %>
    </header>
    <main class="m-0 box-border w-full px-5 flex pb-20">
      <% if notice %>
        <p class="absolute left-0 top-0 text-center text-xl text-white bg-sky-900 p-2.5 z-50"><%= notice %></p>
      <% end%>
      <% if alert %>
        <p class="absolute left-0 top-0 text-center text-xl text-white bg-red-900 p-2.5 z-50"><%= alert %></p>
      <% end%>    
      <%= yield %>
    </main>
  </body>
</html>